<a href="https://colab.research.google.com/github/agustinargallardo-data/financial-intelligence-app/blob/main/notebooks/01_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploratory Data Analysis (EDA)
Initial exploration of income and expense data.

In [25]:
!git clone https://github.com/agustinargallardo-data/financial-intelligence-app.git

fatal: destination path 'financial-intelligence-app' already exists and is not an empty directory.

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("financial-intelligence-app/data/transactions.csv")

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         12 non-null     object
 1   amount       12 non-null     object
 2   type         12 non-null     object
 3   category     12 non-null     object
 4   description  11 non-null     object
dtypes: object(5)
memory usage: 612.0+ bytes

In [29]:
df.groupby("type")["amount"].sum()

type
expense    30050120801506040100150
income                     1200200
rent                       expense
Name: amount, dtype: object

In [30]:
expenses = df[df["type"]== "expense"]
expenses.groupby("category")["amount"].sum()

category
education            150
entertrainment    120100
food               30060
health                80
savings              150
transport           5040
Name: amount, dtype: object

## Initial Insights
- Total expenses are higher than income in this period.
- Food and rent represent the largest expense categories.